class Constants:
    INTENT_LABEL = 'intent'
    TEXT_LABEL = 'text'
    QUESTION_LABEL = 'question'
    ANSWER_LABEL = 'answer'
    CLEANED_LABEL = 'cleaned text'
    NUMBER_LABEL = 'number'
    WHITELIST_LABEL = 'whitelist'
    HOBBYLIST_LABEL = 'hobbylist'
    DATA_FILE_DIR = './data/'
    MODELS_FILE_DIR = './models/'
    MODELS_FILE_NAME = '_model.pkl'
    VECTOR_FILE_NAME = '_vetor.pkl'
    TFDATA_FILE_NAME = '_tfData.pkl'
    ORIDATA_FILE_NAME = '_data.pkl'
    TRANS_MODEL_FILE_PATH = '_transModel.pkl'
    INTENT_DATASET_FILE_NAME = 'dataset.csv'
    INTENT_ANSWER_FILE_NAME = 'answer.csv'
    INTENT_DATASET_PREPROCESSED_INDEX = 'preprocessed_'
    # ANSWER_DATASET_FILE_NAME = 'preprocessed_dataset.csv'
    INTENT_LABEL_FILEPATH = './config/intent_labels.json'
    USER_LIST_FILEPATH = './config/user_list.json'
    ANSWER_FILEPATH = './data/answer.csv'
    DATA_CSV_FILE_NAME = '_data.csv'
    STOPWORDS_FILEPATH = './data/stopwords.txt'
    SPECIAL_SENTENCES_FILEPATH = './data/special_sentences.txt'
    SPLIT_TEST_SIZE = 0.2
    SPLIT_VALIDATION_SIZE = 0.1
    RANDOM_RATE_1 = 1
    TOTAL_INTENT_NUM = 4
    SPLIT_LINE_LENGTH = 80
    DEFAULT_ANSWER = "Sorry. I couldn't find a suitable response. Can you rephrase your question?"
